services:
  minizinc-python-server:
    container_name: minizinc-python-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_HOST=localhost
      # - SPRING_HOST=java-spring-server
      - SPRING_PORT=8080
      - OT_HOST=localhost
      - OT_PORT=9091
      - PASSWORD=4321
      - SOLVER=gecode
    networks:
      - tfo-net
    ports:
      - 9091:9091
    restart: always

networks:
  tfo-net:
    external: true
