services:
  minizinc-python-server:
    container_name: minizinc-python-server
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - tfo-net
    ports:
      - 9091:9091
    restart: always

networks:
  tfo-net:
    external: true
